name: Deploy to S3
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.19.1'

      - run: npm ci

      - run: rm -rf dist && npm run build

      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --exclude "sitemap.xml" --cache-control max-age=31536000 --exclude "robots.txt" --exact-timestamps
        env:
          AWS_S3_BUCKET: ${{ secrets.ACCOUNT_MGT_AWS_S3_BUCKET }}
          AWS_REGION: ${{ vars.GH_ACTION_AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.GH_ACTION_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.GH_ACTION_AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'dist'
